#!/usr/bin/env ruby
#coding:utf-8
require 'lightmare-exlink'

File.write '~tmp.lm', ARGV[0]
EasyLine.translate(name: '~tmp')
json = File.read '~tmp.json'
File.delete '~tmp.lm'
File.delete '~tmp.json'
puts json