#!/usr/bin/env ruby
#coding:utf-8
require 'lightmare-exlink'
require 'rexml/document'

File.write '~tmp.lm', ARGV[0]
EasyLine.translate(name: '~tmp',format: :xml)
xml = File.read '~tmp.xml'
pxml = ''
REXML::Document.new(xml).write pxml, indent=2
File.delete '~tmp.lm'
File.delete '~tmp.xml'
puts pxml