#!/usr/bin/env ruby
#coding:utf-8

exit unless ARGV[0]
tag  = ARGV[0].split("/")
dir  = tag[0..-2].join('/')
yang = tag[-1]
yin  = yang.gsub('.yang','.yin')
flow = "cd #{dir};pyang -f yin -o #{yin} #{yang} 2>> #{Dir.pwd}/yang-translate.log;mv #{yin} #{Dir.pwd}/#{yin}"
system flow
